name: "Terraform validate"
run-name: "Terraform validate triggered by a ${{ github.event_name}} event."

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  discover-modules:
    runs-on: [ubuntu-latest]
    outputs:
      modules-list: ${{ steps.set-modules-list.outputs.modules-list }}
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v5
        
      - name: "Discover Terraform Modules"
        id: set-modules-list
        run: |
          echo "Finding directories in ./modules"
          dirts=$(find ./modules -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R . | jq -s . | jq -c .)
          echo "Found directories: $dirts"
          echo "modules-list=$dirts" >> $GITHUB_OUTPUT
          
      - name: Summary
        run: |
          {
            echo "### Discovered Modules"
            echo "<details><summary>Modules</summary>"
            echo ${{ steps.set-modules-list.outputs.modules-list }}
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY


  discover-products:
    runs-on: [ubuntu-latest]
    outputs:
      products-list: ${{ steps.set-products-list.outputs.products-list }}
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v5

      - name: "Discover Terraform Products"
        id: set-products-list
        run: |
          echo "Finding directories in ./products"
          dirts=$(find ./products -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R . | jq -s . | jq -c .)
          echo "Found directories: $dirts"
          echo "products-list=$dirts" >> $GITHUB_OUTPUT

      - name: Summary
        run: |
          {
            echo "### Discovered Products"
            echo "<details><summary>Products</summary>"
            echo ${{ steps.set-products-list.outputs.products-list }}
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY

  validate-modules:
    needs: discover-modules
    name: "Terraform Validate Modules"
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        module: ${{ fromJson(needs.discover-modules.outputs.modules-list) }}
    uses: nicolas-furtadods/all-repos-tooling-private/.github/workflows/azure_terraform_workflow.yml@master
    with:
      environment: azure-environment
      terraform-version: "1.5.2"
      terraform-working-directory: "modules/${{ matrix.module }}/"
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  validate-products:
    needs: discover-products
    name: "Terraform Validate Products"
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        module: ${{ fromJson(needs.discover-products.outputs.products-list) }}
    uses: nicolas-furtadods/all-repos-tooling-private/.github/workflows/azure_terraform_workflow.yml@master
    with:
      environment: azure-environment
      terraform-version: "1.5.2"
      terraform-working-directory: "products/${{ matrix.module }}/"
    secrets: 
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}